# Generated by Django 6.1 on 2026-08-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
