# Generated by Django 6.1 on 2026-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='default_next_is_ending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='default_next_question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='logic_rules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
