# Generated by Django 6.1 on 2026-08-13 14:08

import uuid
from django.db import migrations


def convert_legacy_logic_to_rules(apps, schema_editor):
    """
    Convert existing Question.logic ({if_option_id, goto_question_id}) into the new
    logic_rules format. Note: goto_question_id stores the ORDER_INDEX of the target
    question (not its database id), so we must resolve order_index → question.id first.
    """
    Question = apps.get_model("forms", "Question")

    for q in Question.objects.exclude(logic=None):
        old = q.logic
        if not isinstance(old, dict):
            continue

        if_opt = old.get("if_option_id")
        goto_order = old.get("goto_question_id")

        if if_opt is None or goto_order is None:
            continue

        # Resolve order_index → question.id within the same form
        target = Question.objects.filter(
            form_id=q.form_id, order_index=goto_order
        ).first()
        if target is None:
            # Stale reference — skip rather than create a broken rule
            continue

        q.logic_rules = [
            {
                "id": str(uuid.uuid4()),
                "condition": {"operator": "equals", "value": str(if_opt)},
                "target_question_id": target.id,
                "target_is_ending": False,
            }
        ]
        q.save(update_fields=["logic_rules"])


def reverse_convert(apps, schema_editor):
    # Reversing is a no-op — we leave logic_rules as-is and the old logic field is untouched
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_add_logic_rules_fields"),
    ]

    operations = [
        migrations.RunPython(
            convert_legacy_logic_to_rules,
            reverse_code=reverse_convert,
        ),
    ]
