# Generated by Django 6.1 on 2026-08-14 05:34

import django.db.models.deletion
from django.db import migrations, models

def backfill_pages(apps, schema_editor):
    Question = apps.get_model('forms', 'Question')
    Page = apps.get_model('forms', 'Page')
    
    for question in Question.objects.all():
        # Create a page for this question
        new_page = Page.objects.create(
            form=question.form,
            order_index=question.order_index
        )
        question.page = new_page
        question.order_in_page = 0
        question.save(update_fields=['page', 'order_in_page'])


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_convert_legacy_logic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order_index', 'order_in_page']},
        ),
        migrations.AddField(
            model_name='question',
            name='order_in_page',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='forms.form')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.page'),
        ),
        migrations.RunPython(backfill_pages, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='question',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.page'),
        ),
    ]
